### ISSUE TITLE
HttpUtil.doGet(ApiList.queryMatchInfo).get("data");返回null

### ISSUE THREAD

**Issue by hortonwei** [JunzhouLiu/bilibili-match-prediction#12]
IDEA执行日志：

2021-04-05 18:58:03 INFO  : 未扫描到外部配置文件，即将加载默认配置文件【此提示仅针自行部署的Linux用户，普通用户请忽略】
2021-04-05 18:58:03 INFO  : 读取配置文件成功
2021-04-05 18:58:03 INFO  : Config{skipDailyTask=false, predictNumberOfCoins=15, minimumNumberOfCoins=30}
2021-04-05 18:58:03 INFO  : 2021-04-05 18:58:03
2021-04-05 18:58:03 DEBUG : 任务启动中
2021-04-05 18:58:03 INFO  : ------登录检查开始------
2021-04-05 18:58:04 INFO  : Cookies有效，登陆成功
2021-04-05 19:35:09 INFO  : 未配置server酱,本次执行不推送日志到微信
2021-04-05 19:35:09 INFO  : 未配置Telegram,本次执行不推送日志到Telegram
Exception in thread "main" java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at top.misec.task.UserCheck.run(UserCheck.java:33)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:30)
	at top.misec.Main.main(Main.java:39)
Disconnected from the target VM, address: '127.0.0.1:9688', transport: 'socket'

Process finished with exit code 1

**Comment by JunzhouLiu** [comment]
执行的太晚了 今天已经没有可参与预测的比赛了
